In [3]:
import numpy as np

#check numpy version
numpy_version = np.__version__
print(F"Numpy version:{numpy_version}")

#check available method
print(dir(np))

Numpy version:1.23.5
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__

### Creating int numpy arrays

In [4]:
# creating python list
python_list = [1,2,3,4,5]

# check the data type 
print('Type:', type(python_list))

print(python_list)

two_demensional_list = [[0,1,2], [3,4,5], [6,7,8]]
print(two_demensional_list)

# creating numpy (Numerical python) array from python list

numpy_array_from_list = np.array(python_list)
print('Type:', type(numpy_array_from_list))
print(numpy_array_from_list)


Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
Type: <class 'numpy.ndarray'>
[1 2 3 4 5]


### Creating float numpy arrays

In [12]:
numpy_array_from_list2 = np.array(python_list, dtype=float)
print(numpy_array_from_list2)

[1. 2. 3. 4. 5.]


### Creating boolean numpy arrays

In [19]:
numpy_bool_array_ = np.array([0,-1,-1,0,0], dtype=bool)
print(numpy_bool_array_)

[False  True  True False False]


### Creating multidimensional array using numpy

In [21]:
numpy_two_dimensional_list = np.array(two_demensional_list)
print(type(numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Converting numpy array to list

In [27]:
np_to_list = numpy_array_from_list.tolist()
two_dimension_np_to_list = numpy_two_dimensional_list.tolist()
print(type(np_to_list))
print(type(two_dimension_np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array:', two_dimension_np_to_list)

<class 'list'>
<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


### Creating numpy array from tuple

In [39]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1,2,3,4,5)
print('Type:', type(python_tuple))
print('python tuple:', python_tuple)

# create numpy array from tuple 
numpy_array_from_tuple = np.array(python_tuple)
print(type(numpy_array_from_tuple))
print('Numpy Array From Tuple:', numpy_array_from_tuple)


Type: <class 'tuple'>
python tuple: (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
Numpy Array From Tuple: [1 2 3 4 5]


### Shape of numpy array

In [54]:
nums= np.array([1,2,3,4,5])
print(nums)
print('shape of nums:', nums.shape)
print(two_demensional_list)
print('shape of numpy two demensional array', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[2,3,4,5], 
                                [4,3,2,5], 
                                [11,23,1,9]])
print('three by four array',three_by_four_array.shape)

[1 2 3 4 5]
shape of nums: (5,)
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
shape of numpy two demensional array (3, 3)
three by four array (3, 4)


### Data type of numpy array

In [ ]:
int_list = [0,2,-1,4,-5]
int_array = np.array(int_list)
float_array = np.array(int_list, dtype=float)

# print 
print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

### Size of a numpy array

In [76]:
mumpy_array_from_list = np.array([1,2,3,4,5])
numpy_two_dimensional_array_from_list = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])

print('The size:', numpy_array_from_list.size)
print('The size:', numpy_two_dimensional_array_from_list.size)

TypeError: 'list' object is not callable

### Mathematical Operation using numpy

In [6]:
print('original:', python_list)
numpy_array = np.array(python_list)
floor_division = numpy_array // 10
print(floor_division)

original: [1, 2, 3, 4, 5]
[0 0 0 0 0]


In [69]:
# Converting int to string
print(numpy_array_from_list.astype('str'))


['1' '2' '3' '4' '5']


### Slicing Numpy array

In [19]:
arr = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(arr)
print('second_row_first_column:', arr[::-1,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
second_row_first_column: [[8 7 6]
 [5 4 3]
 [2 1 0]]


In [52]:
print(arr)
arr[1,1] = 55
arr[1,2] = 88
arr[2,2] = 77
print(arr)

# Numpy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
my_zeros = np.zeros((3,3), dtype=int, order='C')
print(my_zeros)
my_ones = np.ones((3,3), dtype=int, order='C')
print(my_ones)

two = my_ones * 2
print(two)

first_shape  = np.array([[1,2,3], [4,5,6]])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)

[[ 0  1  2]
 [ 3 55 88]
 [ 6  7 77]]
[[ 0  1  2]
 [ 3 55 88]
 [ 6  7 77]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
